services:
    backend: 
        build:
            args: 
                stage: production
                port: 9000
        image: kinich49/expense-tracker-backend:latest
        ports: 
          - "9000:9000"
