name: Continous Delivery

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  continous_delivery_azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD 
        uses: actions/checkout@v2
              
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: kinich49/expense-tracker-rest 
          path: expense-tracker-rest

      - name: Move backend folder
        run: mv expense-tracker-rest ..

      - name: Build PROD
        run: docker-compose -f docker-compose.yml -f azure.yml build  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push backend
        run: docker push kinich49/expense-tracker-backend:latest-azure
  continous_delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD 
        uses: actions/checkout@v2
              
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: kinich49/expense-tracker-rest 
          path: expense-tracker-rest

      - name: Move backend folder
        run: mv expense-tracker-rest ..

      - name: Build PROD
        run: docker-compose -f docker-compose.yml -f production.yml build  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push backend
        run: docker push kinich49/expense-tracker-backend:latest
    
